"const fs = require('fs');"  
"const files = ['docs/plan/22_COMPETITIVE_DEEP_DIVE.json', 'docs/plan/29_DEPLOYMENT_GUIDE.json'];"  
"files.forEach(file => {"  
"  try {"  
"    JSON.parse(fs.readFileSync(file, 'utf8'));"  
"    console.log(file + ': OK');"  
"  } catch(e) {"  
"    console.log(file + ': ERROR - ' + e.message);"  
"  }"  
"});" 
