"'use client';"  
""  
"import { useTranslations } from 'next-intl';"  
"import { cn } from '@/lib/utils';"  
"import { Button } from '@/components/ui/button';"  
""  
"interface BottomNavProps {"  
"  currentPath?: string;"  
"  onNavigate?: (path: string) => void;"  
"}"  
""  
"const navItems = ["  
"  { path: '/dashboard', icon: '??', label: 'navigation.home' },"  
"  { path: '/battle', icon: '??', label: 'navigation.battle' },"  
"  { path: '/units', icon: '??', label: 'navigation.units' },"  
"  { path: '/economy', icon: '??', label: 'navigation.economy' },"  
"  { path: '/valor', icon: '?', label: 'navigation.valor' },"  
"];"  
""  
"export function BottomNav({ currentPath = '/dashboard', onNavigate }: BottomNavProps) {"  
"  const t = useTranslations('navigation');"  
""  
"  return ("  
"    <div className=\"fixed bottom-0 left-0 right-0 z-50 bg-background border-t border-border\">"  
"      <div className=\"flex justify-around items-center h-16 px-2\">"  
"        {navItems.map((item) => ("  
"          <Button"  
"            key={item.path}"  
"            variant={currentPath === item.path ? 'default' : 'ghost'}"  
"            size=\"icon\""  
"            className={cn("  
"              'flex flex-col items-center justify-center h-full',"  
"              currentPath === item.path "  
"                ? 'text-primary-foreground' "  
"                : 'text-muted-foreground hover:text-foreground'"  
"            )}"  
"            onClick={() => onNavigate?.(item.path)}"  
"          >"  
"            <span className=\"text-xl mb-1\">{item.icon}</span>"  
"            <span className=\"text-xs\">{t(item.label.split('.')[1])}</span>"  
"          </Button>"  
"        ))}"  
"      </div>"  
"    </div>"  
"  );"  
"}" 
